"""
agent_family.auth.oauth2
==========================

Google OAuth2 flow management.

Supports two modes:
  WebOAuth2Flow   – PKCE-ready web flow for the FastAPI server (browser redirect)
  GoogleOAuth2Manager – legacy singleton kept for CLI/test compatibility
"""

from __future__ import annotations

import logging
import os
import threading
import time
from typing import Any

import google.auth.transport.requests
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow, InstalledAppFlow

from agent_family.auth.token_store import EncryptedTokenStore

logger = logging.getLogger(__name__)

# Required Google API scopes for the web flow
WEB_SCOPES = [
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/calendar.events",
    "https://www.googleapis.com/auth/tasks",
]


def _mask(token: str | None) -> str:
    if not token:
        return "(none)"
    return token[:6] + "****" + token[-4:]


def _build_client_config(redirect_uri: str | None = None) -> dict:
    client_id = os.getenv("GOOGLE_CLIENT_ID")
    client_secret = os.getenv("GOOGLE_CLIENT_SECRET")
    if not client_id or not client_secret:
        raise ValueError(
            "GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET environment variables are required."
        )
    redirect = redirect_uri or os.getenv(
        "OAUTH_REDIRECT_URI", "http://localhost:8000/auth/callback"
    )
    return {
        "web": {
            "client_id": client_id,
            "client_secret": client_secret,
            "project_id": "agent-family",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "redirect_uris": [redirect],
        }
    }


# ---------------------------------------------------------------------------
# Web OAuth2 Flow (for FastAPI server — browser-based)
# ---------------------------------------------------------------------------


class WebOAuth2Flow:
    """
    Stateless helper that builds Google OAuth2 URLs for the web flow
    and exchanges authorization codes for credentials.

    Each request creates a fresh Flow object (the state token is validated
    server-side by the session / query parameter).
    """

    @staticmethod
    def get_authorization_url(state: str) -> str:
        """
        Build the Google consent URL to redirect the browser to.

        Parameters
        ----------
        state:
            An opaque CSRF token generated by the caller (stored in session).
        """
        redirect_uri = os.getenv("OAUTH_REDIRECT_URI", "http://localhost:8000/auth/callback")
        flow = Flow.from_client_config(
            _build_client_config(redirect_uri),
            scopes=WEB_SCOPES,
            redirect_uri=redirect_uri,
            autogenerate_code_verifier=False,
        )
        # access_type=offline → we receive a refresh_token
        # prompt=consent → forces consent so we always get refresh_token
        auth_url, _ = flow.authorization_url(
            access_type="offline",
            prompt="consent",
            state=state,
            include_granted_scopes="true",
        )
        logger.info("Generated OAuth2 authorization URL (state=%s****)", state[:8])
        return auth_url

    @staticmethod
    def exchange_code(code: str) -> dict[str, Any]:
        """
        Exchange an authorization code for tokens.

        Returns a dict with keys:
          access_token, refresh_token, id_token, expiry_timestamp
        """
        redirect_uri = os.getenv("OAUTH_REDIRECT_URI", "http://localhost:8000/auth/callback")
        flow = Flow.from_client_config(
            _build_client_config(redirect_uri),
            scopes=WEB_SCOPES,
            redirect_uri=redirect_uri,
            autogenerate_code_verifier=False,
        )
        flow.fetch_token(code=code)
        creds = flow.credentials

        expiry_ts = creds.expiry.timestamp() if creds.expiry else None

        logger.info(
            "Token exchange success: access_token=%s refresh_token=%s",
            _mask(creds.token),
            _mask(creds.refresh_token),
        )
        return {
            "access_token": creds.token,
            "refresh_token": creds.refresh_token,
            "id_token": creds.id_token,
            "expiry_timestamp": expiry_ts,
        }

    @staticmethod
    def refresh_token(refresh_token_str: str) -> dict[str, Any]:
        """
        Use a stored refresh_token to obtain a fresh access_token.
        Called automatically by the server when a 401 is intercepted.
        """
        client_id = os.getenv("GOOGLE_CLIENT_ID")
        client_secret = os.getenv("GOOGLE_CLIENT_SECRET")
        creds = Credentials(
            token=None,
            refresh_token=refresh_token_str,
            token_uri="https://oauth2.googleapis.com/token",
            client_id=client_id,
            client_secret=client_secret,
            scopes=WEB_SCOPES,
        )
        request = google.auth.transport.requests.Request()
        creds.refresh(request)

        expiry_ts = creds.expiry.timestamp() if creds.expiry else None

        logger.info(
            "Token refreshed successfully: new_access_token=%s",
            _mask(creds.token),
        )
        return {
            "access_token": creds.token,
            "expiry_timestamp": expiry_ts,
        }


# ---------------------------------------------------------------------------
# Legacy CLI singleton (kept for runner.py and tests)
# ---------------------------------------------------------------------------


class GoogleOAuth2Manager:
    """Thread-safe singleton for managing Google OAuth2 flows (CLI mode)."""

    _instance: GoogleOAuth2Manager | None = None
    _lock = threading.Lock()

    def __new__(cls, *args: Any, **kwargs: Any) -> GoogleOAuth2Manager:
        with cls._lock:
            if cls._instance is None:
                cls._instance = super().__new__(cls)
                cls._instance._init_once()
            return cls._instance

    @classmethod
    def get_instance(cls) -> GoogleOAuth2Manager:
        return cls()

    @classmethod
    def reset_singleton(cls) -> None:
        """Test-only method to clear the singleton instance."""
        with cls._lock:
            cls._instance = None

    def _init_once(self) -> None:
        self.rlock = threading.RLock()
        self.token_store = EncryptedTokenStore()

    def _get_client_config_installed(self) -> dict:
        client_id = os.getenv("GOOGLE_CLIENT_ID")
        client_secret = os.getenv("GOOGLE_CLIENT_SECRET")
        if not client_id or not client_secret:
            raise ValueError(
                "GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET environment variables are required."
            )
        return {
            "installed": {
                "client_id": client_id,
                "project_id": "agent-family",
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token",
                "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                "client_secret": client_secret,
                "redirect_uris": ["http://localhost"],
            }
        }

    def get_credentials(self, service_name: str, scopes: list[str] | None = None) -> Credentials:
        """Gets valid credentials for the given service, prompting the user if necessary."""
        _scopes = scopes or WEB_SCOPES
        with self.rlock:
            creds = self.token_store.load(service_name)
            if creds and creds.valid:
                return creds

            logger.info("Initiating OAuth2 flow for '%s'...", service_name)
            client_config = self._get_client_config_installed()
            flow = InstalledAppFlow.from_client_config(client_config, _scopes)
            creds = flow.run_local_server(
                port=0,
                success_message="Authentication successful! You can close this window.",
            )
            self.token_store.save(service_name, creds)
            return creds

    def revoke(self, service_name: str) -> None:
        with self.rlock:
            self.token_store.delete(service_name)
